apiVersion: v1
kind: Service
metadata:
  name: mirror
  labels:
    app: mirror
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: server-http
      protocol: TCP
    - name: rtmp
      port: 1935
      targetPort: server-rtmp
      protocol: TCP
  selector:
    app: mirror

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mirror
  labels:
    app: mirror
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: mirror
    spec:
      containers:
      - name: mirror-server
        image: noumaan/mirror-server:2
        imagePullPolicy: Always
#        command:
#          - "bash"
#          - "-c"
#          - "tail -f /etc/hostname"
        ports:
        - name: server-http
          containerPort: 80
          protocol: TCP
        - name: server-rtmp
          containerPort: 1935
          protocol: TCP

      restartPolicy: Always
