version: '3'

services:

  mirror:
    build: .
    image: noumaan/mirror-server:2
    # volumes:
#      - ./tools/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./dist:/var/www/html
#    networks:
#      - dev-network
    ports:
      - '1935:1935'
      - '8080:80'
